changelog:
  exclude:
    labels:
      - Build
      - github_actions
  categories:
    - title: Features
      labels:
        - Improvement
        - Performance
    - title: Bug fixes
      labels:
        - Bug
    - title: Dependency updates
      labels:
        - dependencies
        - library-update
        - sbt-plugin-update
    - title: Miscellaneous
      labels:
        - '*'
