pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalaplatform/scala:0.6
    pull: true
    volumes:
      - /platform:/keys
    commands:
      - git fetch --tags && git log | head -n 20
      - ./bin/checkCLA.sh
      - ./bin/scalafmt --test
      - sbt $CI_TEST

  publish:
    image: scalaplatform/scala:0.6
    pull: true
    volumes:
      - /platform:/keys
    commands:
      - ./bin/bintray.sh
    when:
      event: push
      branch: [master]

  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    username: noreply@drone.geirsson.com
    password: ${MAILGUN_PASSWORD}
    from: noreply@drone.geirsson.com
    recipients:
      - olafurpg@gmail.com
      - xeno.by@gmail.com
    when:
      event: push
      branch: [master]
      status: [changed, failure]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

matrix:
  include:
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.11.8
      CI_PUBLISH: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.11.8
      SCALA_JS: true
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.12.1
    - CI_TEST: ci-fast
      CI_SCALA_VERSION: 2.12.1
      SCALA_JS: true
    - CI_TEST: ci-slow
      CI_SCALA_VERSION: 2.11.8
    - CI_TEST: ci-slow
      CI_SCALA_VERSION: 2.12.1

