clone:
  depth: 50
  tags: true
  recursive: true
build:
  tests:
    image: ensime/ensime:v2.x-cache
    pull: true
    environment:
      - COURSIER_CACHE=/drone/cache/coursier
    commands:
      - git log | head -n 20
      - ./bin/checkCLA.sh
      - ./bin/scalafmt --test
      - sbt -Dsbt.ivy.home=/drone/cache/ivy2 ci
  publish:
    image: ensime/ensime:v2.x-cache
    environment:
      - SONATYPE_USERNAME=$$SONATYPE_USERNAME
      - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
      - GITHUB_USERNAME=$$GITHUB_USERNAME
      - GITHUB_PASSWORD=$$GITHUB_PASSWORD
      - BINTRAY_USERNAME=$$BINTRAY_USERNAME
      - BINTRAY_API_KEY=$$BINTRAY_API_KEY
      - MAILGUN_PASSWORD=$$MAILGUN_PASSWORD
    commands:
      - ./bin/bintray.sh
    when:
      event: push
      branch: [master, 2.x]
cache:
  mount:
    - /drone/cache
notify:
  email:
    from: noreply@drone.geirsson.com
    host: smtp.mailgun.org
    username: noreply@drone.geirsson.com
    password: $MAILGUN_PASSWORD
    recipients:
      - olafurpg+scalameta-ci@gmail.com
