pipeline:
  # Fetch folders from distributed cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalacenter/scala-extras:1.0
    pull: true
    commands:
      - git fetch --tags && git log | head -n 20
      - ./bin/checkCLA.sh
      - ./bin/scalafmt --test
      - sbt $TEST

  publish:
    image: scalacenter/scala-extras:1.0
    environment:
      - SONATYPE_USERNAME=$$SONATYPE_USERNAME
      - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
      - GITHUB_USERNAME=$$GITHUB_USERNAME
      - GITHUB_PASSWORD=$$GITHUB_PASSWORD
      - BINTRAY_USERNAME=$$BINTRAY_USERNAME
      - BINTRAY_API_KEY=$$BINTRAY_API_KEY
      - MAILGUN_PASSWORD=$$MAILGUN_PASSWORD
    commands:
      - ./bin/bintray.sh
    when:
      event: push
      branch: [master, 2.x]

  # Save folders in distributed cache
  sftp_cache_rebuild:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

matrix:
  TEST:
    - ci-fast
    - ci-slow

