clone:
  depth: 50
  tags: true
  recursive: true
build:
  tests:
    image: ensime/ensime:v2.x-cache
    pull: true
    environment:
      - COURSIER_CACHE=/drone/cache/coursier
    commands:
      - ./bin/checkCLA.sh
      - sbt -Dsbt.ivy.home=/drone/cache/ivy2 ++$SCALA_VERSION test doc
  publish:
    image: ensime/ensime:v2.x-cache
    environment:
      - SONATYPE_USERNAME=$$SONATYPE_USERNAME
      - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
      - GITHUB_USERNAME=$$GITHUB_USERNAME
      - GITHUB_PASSWORD=$$GITHUB_PASSWORD
      - BINTRAY_USERNAME=$$BINTRAY_USERNAME
      - BINTRAY_API_KEY=$$BINTRAY_API_KEY
    commands:
      - ./bin/bintray.sh
    when:
      event: push
      branch: [master, 2.x]
matrix:
  SCALA_VERSION:
    - 2.11.8
    - 2.12.0
cache:
  mount:
    - /drone/cache
